os: linux
dist: focal
language: java

services:
  - docker

env:
  jobs:
    - DOCKER_IMAGE=stadlerpeter/existdb
    - DOCKER_IMAGE=stadlerpeter/existdb:3.3.0
    - DOCKER_IMAGE=stadlerpeter/existdb:5.2

before_install:
  - docker pull ${DOCKER_IMAGE}
  - ant xar
  - curl http://exist-db.org/exist/apps/public-repo/public/functx-1.0.1.xar -o build/functx-1.0.1.xar
  - docker create --name exist ${DOCKER_IMAGE}
  - for i in build/*.xar ; do docker cp $i exist:/opt/exist/autodeploy/ ; done
  - docker start exist
  - i=0 ; while (! docker inspect exist | grep -e Status....healthy) ; do if ((i > 30)) ; then echo ' **** timeout ... aborting **** ' ; exit 1 ; else sleep 5 ; echo waiting for container ... ; i=$((i+1)) ; fi ; done
  - docker exec -it exist cat webapp/WEB-INF/logs/exist.log
  - docker exec -it exist curl "http://127.0.0.1:8080/exist/apps/WeGA-WebApp-lib/testing/run-tests.xql" > report.xml

script: 
  - grep testsuite report.xml && (! grep 'failures="[1-9]' report.xml) && (! grep 'errors="[1-9]' report.xml) 

after_failure:
  - cat report.xml
